export default {
  props: {
    broken: {
      type: Boolean,
      default: false
    }
  },
  data() {
    return {
      showImageDilog: false,
      imageUrl: '',
      maxHeight: 600,
      newArea: '',
      currentNotification: null,
      currentProduct: {},
      brokenPropotionArr: [],
      totalPrice: 0,
      tableData: [
        {
          propotion: 53.33,
          code: '1191A',
          type_name: 'Ochi',
          size: '30 * 90',
          base_price: 2,
          base_price_changed: 2,
          sum: 0,
          sum_kassa: 0,
          price_by: false,
          broken: false,
          packTotalArea: '',
          item_num: '',
          pack_num: '',
          over_pack_num: '',
          wight_of_one_packet: 28,
          weight_of_an_item: 4.6,
          weight: '',
          area_of_one_packet: 1.62,
          area_of_an_item: 0.27,
          number_of_items: 6
        },
        {
          propotion: 26.67,
          code: '1191D',
          type_name: 'Decor',
          size: '30 * 90',
          broken: false,
          base_price: 4,
          base_price_changed: 4,
          sum_kassa: 0,
          sum: 0,
          price_by: false,
          packTotalArea: '',
          item_num: '',
          pack_num: '',
          over_pack_num: '',
          wight_of_one_packet: 28,
          weight_of_an_item: 4.6,
          weight: '',
          area_of_one_packet: 1.62,
          area_of_an_item: 0.27,
          number_of_items: 6
        },
        {
          propotion: 53.33,
          broken: true,
          code: '1191BR',
          type_name: 'Ochi (Singan)',
          size: '30 * 90',
          base_price: 2,
          base_price_changed: 2,
          sum: 0,
          sum_kassa: 0,
          price_by: false,
          packTotalArea: '',
          item_num: '',
          pack_num: '',
          over_pack_num: '',
          wight_of_one_packet: 28,
          weight_of_an_item: 4.6,
          weight: '',
          area_of_one_packet: 1.62,
          area_of_an_item: 0.27,
          number_of_items: 6
        },
        {
          propotion: 20,
          code: '1191C',
          type_name: 'Pol',
          size: '30 * 30',
          base_price: 6,
          base_price_changed: 6,
          sum_kassa: 0,
          sum: 0,
          packTotalArea: '',
          item_num: '',
          pack_num: '',
          broken: false,
          price_by: false,
          over_pack_num: '',
          wight_of_one_packet: 25,
          weight_of_an_item: 2.28,
          weight: '',
          area_of_one_packet: 0.99,
          area_of_an_item: 0.09,
          number_of_items: 11
        }

      ],
      tableData1: [
        {
          propotion: 49,
          code: '1191A',
          type_name: 'Ochi',
          size: '30 * 60',
          base_price: 3000,
          sum: 0,
          packTotalArea: '',
          item_num: '',
          pack_num: '',
          over_pack_num: '',
          wight_of_one_packet: 25,
          weight_of_an_item: 3.125,
          weight: '',
          area_of_one_packet: 1.44,
          area_of_an_item: 0.18,
          number_of_items: 8
        },
        {
          propotion: 25.2,
          code: '1191B',
          type_name: "To'qi",
          size: '30 * 60',
          packTotalArea: '',
          base_price: 1200,
          item_num: '',
          pack_num: '',
          sum: 0,
          over_pack_num: '',
          wight_of_one_packet: 25,
          weight_of_an_item: 3.125,
          weight: '',
          area_of_one_packet: 1.44,
          area_of_an_item: 0.18,
          number_of_items: 8
        },
        {
          propotion: 5.3,
          code: '1191C',
          type_name: 'Dekor',
          size: '30 * 60',
          packTotalArea: '',
          item_num: '',
          base_price: 304,
          sum: 0,
          pack_num: '',
          over_pack_num: '',
          wight_of_one_packet: 25,
          weight_of_an_item: 3.125,
          weight: '',
          area_of_one_packet: 1.44,
          area_of_an_item: 0.18,
          number_of_items: 8
        },
        {
          propotion: 14.85,
          code: '1191D',
          type_name: 'Pol',
          size: '30 * 30',
          packTotalArea: '',
          item_num: '',
          pack_num: '',
          over_pack_num: '',
          base_price: 2000,
          sum: 0,
          wight_of_one_packet: 21,
          weight_of_an_item: 1.4,
          weight: '',
          area_of_one_packet: 1.35,
          area_of_an_item: 0.09,
          number_of_items: 15
        },
        {
          propotion: 1.65,
          code: '1191F',
          type_name: 'Friz',
          size: '30 * 6',
          packTotalArea: '',
          item_num: '',
          pack_num: '',
          base_price: 300,
          sum: 0,
          over_pack_num: '',
          wight_of_one_packet: 21,
          weight_of_an_item: 1.4,
          weight: '',
          area_of_one_packet: 0.72,
          area_of_an_item: 0.018,
          number_of_items: 40
        },
        {
          propotion: 1.1,
          code: '1191S',
          type_name: 'Sigara',
          size: '30 * 2',
          packTotalArea: '',
          item_num: '',
          base_price: 3401,
          pack_num: '',
          sum: 0,
          over_pack_num: '',
          wight_of_one_packet: 10,
          weight_of_an_item: 0.1,
          weight: '',
          area_of_one_packet: 0.6,
          area_of_an_item: 0.006,
          number_of_items: 100
        },
        {
          propotion: 2.76,
          code: '1191P',
          type_name: 'Plintus',
          size: '30 * 10',
          packTotalArea: '',
          item_num: '',
          base_price: 3401,
          pack_num: '',
          sum: 0,
          over_pack_num: '',
          wight_of_one_packet: 20,
          weight_of_an_item: 0.1,
          weight: '',
          area_of_one_packet: 18.6,
          area_of_an_item: 0.03,
          number_of_items: 620
        }
      ]
    }
  },
  computed: {
    tableDataComputed() {
      if (this.broken) {
        return this.tableData
      }
      return this.tableData.filter(item => item.broken === this.broken)
    }
  }
}
