export default {
  data() {
    return {
      showImageDilog: false,
      imageUrl: '',
      maxHeight: 600,
      newArea: '',
      currentProduct: {},
      whatIsInserting: [0, 0, 0],
      tableData: [
        {
          code: '1191A',
          spec: 'Ochi',
          size: '30 * 60',
          basePrice: 3000,
          sum: 0,
          packTotalArea: '',
          item_num: '',
          pack_num: '',
          over_pack_num: '',
          pack_weight: 25,
          one_item_weight: 3.125,
          weight: '',
          packArea: 1.44,
          itemArea: 0.18,
          pack_content_num: 8
        },
        {
          code: '1191B',
          spec: "To'qi",
          size: '30 * 60',
          packTotalArea: '',
          basePrice: 1200,
          item_num: '',
          pack_num: '',
          sum: 0,
          over_pack_num: '',
          pack_weight: 25,
          one_item_weight: 3.125,
          weight: '',
          packArea: 1.44,
          itemArea: 0.18,
          pack_content_num: 8
        },
        {
          code: '1191C',
          spec: 'Dekor',
          size: '30 * 60',
          packTotalArea: '',
          item_num: '',
          basePrice: 304,
          sum: 0,
          pack_num: '',
          over_pack_num: '',
          pack_weight: 25,
          one_item_weight: 3.125,
          weight: '',
          packArea: 1.44,
          itemArea: 0.18,
          pack_content_num: 8
        },
        {
          code: '1191D',
          spec: 'Pol',
          size: '30 * 30',
          packTotalArea: '',
          item_num: '',
          pack_num: '',
          over_pack_num: '',
          basePrice: 2000,
          sum: 0,
          pack_weight: 21,
          one_item_weight: 1.4,
          weight: '',
          packArea: 1.35,
          itemArea: 0.09,
          pack_content_num: 15
        },
        {
          code: '1191F',
          spec: 'Friz',
          size: '30 * 6 ',
          packTotalArea: '',
          item_num: '',
          pack_num: '',
          basePrice: 300,
          sum: 0,
          over_pack_num: '',
          pack_weight: 21,
          one_item_weight: 1.4,
          weight: '',
          packArea: 0.72,
          itemArea: 0.018,
          pack_content_num: 40
        },
        {
          code: '1191S',
          spec: 'Sigara',
          size: '30 * 2 ',
          packTotalArea: '',
          item_num: '',
          basePrice: 3401,
          pack_num: '',
          sum: 0,
          over_pack_num: '',
          pack_weight: 10,
          one_item_weight: 0.1,
          weight: '',
          packArea: 0.6,
          itemArea: 0.006,
          pack_content_num: 100
        }
      ]
    }
  }
}
